### ISSUE TITLE
분류모델 테스트 케이스 정리

### ISSUE THREAD

**Issue by pmz-q** [pmz-q/est_wassup_03#32]

**Comment by angie0bb** [comment]
https://docs.google.com/spreadsheets/d/1nJKD8V16bbqxkrELhgn8TSKE7tCzoFhq0VX7vaz_9dU/edit#gid=0

**Comment by pmz-q** [comment]
data preprocessing documentation 끝나고 진행

**Comment by pmz-q** [comment]
yolo 완료, 추후 다른 모델 진행 예정
